In [8]:
import pandas as pd

dataset = pd.read_csv("../../Output Datasets/final_features_otu_summary.csv")
dataset = dataset.transpose()
dataset.columns = dataset.iloc[0]
dataset.columns.name = None
dataset = dataset[1:]
dataset = dataset.reset_index()
dataset.rename(columns={dataset.columns[0]: "OTU"}, inplace=True)
dataset.head()

      OTU      Min.   1st Qu.    Median      Mean   3rd Qu.       Max.
0   Otu15  0.048658  0.905516  1.658197  1.797131  2.496059   5.874629
1   Otu10  0.001916   0.25643  0.789202  1.307279  1.665306  16.591401
2   Otu43       0.0       0.0  0.001498  0.182746  0.088432   3.453704
3  Otu182       0.0       0.0  0.001846  0.081316  0.109209    0.80004
4  Otu189       0.0       0.0  0.089541  0.152005  0.212401   0.891557

In [9]:
taxa = pd.read_excel("../../Output Datasets/Final Selected OTUs.xlsx")
taxa.head()

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,OTU,BAM.Score,Family,Genus,Species
0,Otu15,0.731409,F_Bifidobacteriaceae,G_Bifidobacterium,G_Bifidobacterium_Unclassified
1,Otu10,0.705943,F_Oxalobacteraceae,G_Herbaspirillum,S_Herbaspirillum_huttiense
2,Otu43,0.660650,F_Bacillaceae,G_Bacillus,G_Bacillus_Unclassified
3,Otu182,0.562081,F_Ruminococcaceae,G_Ruminococcus,G_Ruminococcus_Unclassified
4,Otu189,0.556125,F_Porphyromonadaceae,G_Parabacteroides,S_Parabacteroides_distasonis

In [10]:
merged_df = pd.concat([dataset, taxa], axis=1)
merged_df.head()

,OTU,Min.,1st Qu.,Median,Mean,3rd Qu.,Max.,OTU,BAM.Score,Family,Genus,Species
0,Otu15,0.048658,0.905516,1.658197,1.797131,2.496059,5.874629,Otu15,0.731409,F_Bifidobacteriaceae,G_Bifidobacterium,G_Bifidobacterium_Unclassified
1,Otu10,0.001916,0.25643,0.789202,1.307279,1.665306,16.591401,Otu10,0.705943,F_Oxalobacteraceae,G_Herbaspirillum,S_Herbaspirillum_huttiense
2,Otu43,0.0,0.0,0.001498,0.182746,0.088432,3.453704,Otu43,0.660650,F_Bacillaceae,G_Bacillus,G_Bacillus_Unclassified
3,Otu182,0.0,0.0,0.001846,0.081316,0.109209,0.80004,Otu182,0.562081,F_Ruminococcaceae,G_Ruminococcus,G_Ruminococcus_Unclassified
4,Otu189,0.0,0.0,0.089541,0.152005,0.212401,0.891557,Otu189,0.556125,F_Porphyromonadaceae,G_Parabacteroides,S_Parabacteroides_distasonis

In [11]:
merged_df.to_csv("../../Output Datasets/final_features_otu_summary_merged.csv", index=False)